### ISSUE TITLE
Please consider renaming Evaluate() to Contribute()

### ISSUE THREAD

**Issue by stef** [cfrg/draft-irtf-cfrg-voprf#140]
`Contribute` describes the semantics better than the generic `Evaluate` name.

see the discussion here: https://github.com/cfrg/draft-irtf-cfrg-opaque/issues/53

**Comment by alxdavids** [comment]
Hi @stef, thanks for bringing this up. I've taken a look at the discussion. I'm not massively supportive of renaming the Server's participation to `Contribute`. I can see what you mean, because this is a protocol that both participants combine to evaluate a PRF. However, theoretically-speaking, it's the Server that essentially computes the underlying PRF itself. The client specifies an input and then just does some pre-processing and public operations. This is why we currently use `Evaluate`. Moreover, I don't think `Contribute` really conveys the fact that the server is performing a secret-key operation. cc @chris-wood to see what he thinks and to discuss further.

**Comment by chris-wood** [comment]
@stef can you please bring this to the list? I could see changing the name if we were to support threshold OPRFs, for example. But as it stands now, to me, `Contribute` does not better describe the semantics than `Evaluate`, for the reasons that Alex states.

**Comment by stef** [comment]
which list, is there a dedicated list for this proposal or the big cfrg list?

**Comment by chris-wood** [comment]
The CFRG list! :)

**Comment by stef** [comment]
although i subscribed to the list, before writing to it i reviewed the academic literature and i apologize for making this noise.
