### ISSUE TITLE
Does the 'dst' for the HashToCurve func need to be different for each mode?

### ISSUE THREAD

**Issue by claucece** [cfrg/draft-irtf-cfrg-voprf#165]

**Comment by chris-wood** [comment]
There are several ways we could achieve domain separation. For consistency with the other functions, I'd recommend augmenting the input to `HashToGroup` with a DST, e.g.:

```
def Blind(input):
  r = GG.RandomScalar()
  blindDST = "VOPRF05-Finalize-" || self.contextString
  P = GG.HashToGroup(input || I2OSP(len(blindDST), 2) || blindDST)
```

**Comment by claucece** [comment]
Mmm.. on some of the functions, this make  some sense. In others, we can add:

```
def VerifyFinalize(skS, input, info, output):
  DST = self.contextString
  T = GG.HashToGroup(input || dst)
  (...)

```

but, the hash-to-group draft specifies a minimum of 16 bytes and that it is recommended that the suite id is included in the dst. 

```
   2.  Tags MUST have nonzero length.  A minimum length of 16 bytes is
       RECOMMENDED to reduce the chance of collisions with other
       applications.
   6.  For applications that use multiple encodings, either to the same
       curve or to different curves, each encoding MUST use a different
       tag.  For this purpose, it is RECOMMENDED to include the
       encoding's Suite ID (Section 8) in the domain separation tag.
       For independent encodings based on the same suite, each tag
       should also include a distinct identifier, e.g., "ENC1" and
       "ENC2".
```

So, something like this can be used:

```
dst = VOPRF05-self.contextString-P521_XMD:SHA-512_SSWU_RO\_`, depending on the suite id
```

**Comment by armfazh** [comment]
Let's step back for a second,
given a named suite, say e.g.  `id = "OPRF(P256,SHA256)" ` 

does this identifier considers the implementation of both verifiable and non-verifiable modes?

- if so, 
 -- then the `dst` used for HashToGroup could be the concatenation of suite id and the mode.
- otherwise,
 -- `OPRF(P256,SHA256)` means only the non-verifiable mode, then we need a suite identifier for the verifiable mode, for example `VOPRF(P256,SHA256)`. Going this way,  `dst` can be equal to the suite id.
