### ISSUE TITLE
Update static DH oracle text

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-voprf#224]
From @hugokraw:

> An attack with Q queries, lowers security by (log Q)/2 bits (not log Q), and it only applies if Q is a divisor of p-1 or p+1. Moreover, the *memory* cost of the attack (not just time) is 2^{p/2-(log(Q)/2}. 

We might also want to update the "use a larger curve" guidance, since whether or not it's needed depends on the feasibility of these attacks. (OPAQUE, for example, is fine to use P-256 and the like.)

More information can be found in [Taylor's writeup](https://mumble.net/~campbell/tmp/20210116/draft-riastradh-staticdh.html) on  "Attacks on Static Diffie-Hellman Oracles".

**Comment by hugokraw** [comment]
My remark quoted above is correct _except_ that memory cost has been reduced to essentially constant (see Taylor's writeup). Communication cost remains infeasible even for those that think of  2^100 time attacks as realistic in some way.

**Comment by LoupVaillant** [comment]
Taylor's writeup spoke of the limitations of the legitimate server, and explicitly ignored communication overhead. Personally, I believe communication overhead provides an even more convincing argument, because of a fundamental limitation of our universe: the speed of light.

Light travels about 30cm per nanosecond. A 1ns round trip thus requires the attacker to be within 15cm of the legitimate server. 10ns allows up to 1.5m. 100ns allows up to 15m. If the attacker can plant their hardware this close to the legitimate server for any length of time, they almost certainly have physical access, and therefore much better attacks at their disposal. For this reason alone, 100ns minimum round trip sounds like a reasonable lower bound.

Another point is that using a bigger curve is not the only way to raise the security of static DH. Since the attacker is limited by the capabilities of the *legitimate* server, applications can limit the number of illegitimate queries with simple (per user) throttling, detect the attack with regular DoS detection tools, or notice something is going on by looking at performance charts or logs.

**Comment by alterstep** [comment]
Close adversary -> other VM on the same machine or backdoor in switch/router! It can happen!
User assume crypto is safe -> not assume applications and users must work around crypto design flaws

**Comment by LoupVaillant** [comment]
> Close adversary -> other VM on the same machine or backdoor in switch/router! It can happen!

I did not think of the VM, though that would be very close to having physical access. Given how hard process isolation is, if the adversary shares a server with the victim, side channels are probably a more serious threat than the number of possible requests. And even if they aren't, the attacker still has to deal with the limitations of the victim's CPU, virtual or not. My argument about distance is an *addition* to Taylor Campbell's argument about single thread speed.

> User assume crypto is safe -> not assume applications and users must work around crypto design flaws

As much as we'd like to give users a black box that just works, in practice it doesn't work that way. We have to balance between convenience, efficiency, cost, and security. Sometimes we even balance between different kinds of security. Here, using relatively "small" curves (Curve25519, P-256…) that are already in wide use means we can reuse existing implementations (some of which are optimised to the brim and reviewed by the best eyes), and get something running quickly.

If we're telling users "nope, this is not secure enough, use a bigger curve", they may skip OPRF entirely, and end up with even worse security. If we're telling them "you need to limit the number of queries", they can chose whether that's an acceptable price for using the otherwise convenient option.

Finally, note that OPRFs aren't used in a vacuum. They're inevitably part of protocols, and protocols aren't supposed to be designed by noobs to begin with. PAKEs for instance can easily have lower security requirements from their OPRF, either because they don't entirely rely on it for security (AuCPACE), or because plain old password guessing is the bigger threat to begin with.

**Comment by chris-wood** [comment]
@alxdavids will you have cycles to do a PR for this in the next day or so?

**Comment by alxdavids** [comment]
@chris-wood, not sure I'd have cycles for this before Monday. There was a recent write-up which is formulated as a draft CFRG document, but I'm not sure if it has yet been submitted: https://riastradh.github.io/draft-riastradh-cfrg-staticdh/draft-riastradh-cfrg-staticdh.html. Ultimately, if we could link this discussion outside of VOPRFs, I think this would be a nicer solution.

**Comment by chris-wood** [comment]
@alxdavids any chance you can do this before IETF 111?
