### ISSUE TITLE
aux additional data

### ISSUE THREAD

**Issue by armfazh** [cfrg/draft-irtf-cfrg-voprf#83]
If the only purpose of `aux` additional info is to provide domain separation, then this can be re-engineered and unified together with the other hash functions. Related #79

**Comment by armfazh** [comment]
_Originally posted by @chris-wood in https://github.com/cfrg/draft-irtf-cfrg-voprf/pull/78_
Should we unify around DST instead of `aux`?

**Comment by alxdavids** [comment]
I think we need multiple DSTs. One for the DLEQ proof generation, and then `aux`. However, I think capturing all DST usages under a specific set of guidelines makes sense. The only difference is that Finalize depends on client properties, where as the DLEQ DST should probably be fixed (to something VOPRF ciphersuite-specific) so that the client & server are in agreement.

**Comment by alxdavids** [comment]
Assigning to @chris-wood to do as it is related to #89

**Comment by alxdavids** [comment]
Done: #102
